Мишакова Наталья Сергеевна ПИ-401
urfu-2017/autotests-task-01 pull request #10
Opened 2018-04-09 17:00 UTC by mishakova

2018-05-07 18:46 UTC, zanevskaya requested changes
Привет!
Все хорошо, но сообщения об ошибках должны быть содержательными. Например, "This is not a combination for poker" не говорит нам о том, что на самом деле имелось ввиду кол-во чисел, превышающее 5. Твои сообщения не содержат сути проверки. Исправь.

2018-05-08 05:48 UTC, mishakova commented
Исправила

2018-05-08 10:45 UTC, zanevskaya requested changes
По сообщениям об ошибке - все хорошо, только можно еще уточнить касательно количества: больше или меньше 5, а не просто "is not 5".

И еще нужно добавить негативные проверки - ты проверила, что будет, если в массив мы передадим не число, а что если мы передадим дробное число? Или, например, вместо массива передадим что-то другое?

2018-05-08 15:59 UTC, mishakova commented
Для проверки, что число не дробное есть проверка на то, что вводятся значения именно игрального кубика, т.е. целые значения от 1 до 6

2018-05-10 09:14 UTC, zanevskaya approved these changes
Теперь все хорошо. Работу принимаю.

2018-05-10 09:14 UTC, closed without merging