Мамонов Антон
urfu-2017/autotests-task-01 pull request #13
Opened 2018-04-09 18:48 UTC by graf-m-96

2018-04-15 15:51 UTC, sunkitten13 requested changes
Привет! У тебя не все ветки покрыты тестами. В идеале в Details должно быть 100% покрытие по всем пунктам. Попробуй найти, чего именно не хватает.

2018-04-16 05:47 UTC, graf-m-96 commented
Привет!
Несколько языков в выводе одновременно действительно плохо выглядят😅
Добавил недостающие ветки, кроме 1ой
Эта ветка выполняется, если аргумент некорректный, но разработчик допустил ошибку при написании библиотеки и не учёл такой случай
( https://github.com/graf-m-96/autotests-task-01/blob/master/lib/getPokerHand.js#L29 )

2018-04-22 18:37 UTC, sunkitten13 requested changes
Антон, привет! Одно из условий принятия данного дз: 100% покрытие тестами всех веток, что должно быть отражено в Details. Поэтому надо поправить.
Посмотрела тесты: не хватает негативных проверок. Еще в теории тестирования проходили, что несколько негативных проверок нельзя объединять в один кейс.
Надо поправить.

2018-04-25 10:06 UTC, sunkitten13 requested changes
Привет! Сейчас по тестам хорошо, и по покрытию хорошо, но один момент очень смущает: а где тексты ошибок для каждого негативного кейса? У тебя сейчас везде текст ошибки без конкретики плюс вывод введенного неверного массива (или того, что вместо него). И вот здесь "Должно выброситься исключение для массива, содержащего целые числа меньше 6 " явно опечатка?

2018-04-25 15:39 UTC, graf-m-96 commented
Исправил на более конкретные описания (теперь вывожу ещё некорректный элемент и тип ошибки)
Да, точно, опечатался)

2018-04-28 15:08 UTC, sunkitten13 requested changes
Привет.
Нужно проверять не только факт ошибки, но и текст. У тебя проверяется только факт.

2018-04-30 15:55 UTC, graf-m-96 commented
Добрый вечер!
В прошлый раз не понял замечание
Теперь проверяю ещё тип и сообщение исключения

2018-05-11 12:59 UTC, sunkitten13 approved these changes

2018-05-11 13:00 UTC, closed without merging