Денис Фомин
urfu-2017/autotests-task-01 pull request #14
Opened 2018-04-10 07:49 UTC by ilearnf

2018-04-17 10:50 UTC, sergeeva-a requested changes
Нет негативных проверок

2018-04-18 09:46 UTC, ilearnf commented
да, добавил.

2018-04-28 06:32 UTC, sergeeva-a requested changes

2018-04-28 06:32 UTC, sergeeva-a commented on tests/getPokerHand-test.js
> +
а проверить выпавшие значения? 
граничные, приграничные условия, за пределами границы, не массив, пустые данные и разного типа данные? выпасть могут и цифры в границе, но не подходящие по условию. Попробуй еще раз

2018-04-30 07:52 UTC, ilearnf commented on tests/getPokerHand-test.js
> +
Что значит «проверить выпавшие значения»? Этот тест проверяет, что функция возвращает ожидаемое значение. А граничные случаи в т. ч. проверяют следующие тесты. 
Немассив, поведение на граничных значениях чисел-костей, поведение при неправильном количестве костей (правда, с одной стороны) проверяется. Действительно, стоит добавить пустые данные, проверку на количество костей с другой стороны и добавить ещё типов немассивов.

2018-05-23 12:32 UTC, Zhigalov reviewed
Тебе не хватает пол балла до автомата, закрываю без доработок с половинным баллом. Итого, у тебя автомат.

Сегодня на зачет на приходи, потому что:
>По договорённости с деканатом оценки в зачетки будет ставить Маргарита Шадрина. Она же будет расписываться в документах по проекту. Маргарита сейчас не в городе. Поэтому ставить зачеты мы будем 29 мая (вторник) с 17 до 19 в Пангее (офис Яндекса, 4 этаж). Если предложенное время неудобно для вас, можно найти Маргариту в университете 28 мая (понедельник) во второй половине дня.

2018-05-23 12:32 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +	    var res = () => getPokerHand([6, 6, 6, 6 ,6]);
У кубика шесть граней, шестёрка - допустимое значение.

2018-05-23 12:32 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +
Не хватает проверки на случай, если передали дробное число.

2018-05-23 12:32 UTC, closed without merging

2018-05-23 12:56 UTC, ilearnf commented
спасибо большое за оперативность! в таком случае подойду к Маргарите.