Шельпяков Андрей
urfu-2017/autotests-task-01 pull request #19
Opened 2018-04-10 20:41 UTC by Shancle

2018-04-12 15:03 UTC, Zhigalov requested changes
Хорошо, но нужны небольшие доработки.

2018-04-12 15:03 UTC, Zhigalov commented on lib/getPokerHand.js
> +    return typeof(value) == "number" && value >= 1 && value <= 6;
```js
typeof(1.2) == "number" // true
```
Однако, это не допустимое условие. Нужно сделать проверку более строгой

2018-04-12 15:03 UTC, Zhigalov commented on lib/getPokerHand.js
> +function getTwoLargestValue(array) {
Можно просто отсортировать массив методом `.sort()` и взять последние два элемента

2018-04-16 15:17 UTC, Shancle commented on lib/getPokerHand.js
> +    return typeof(value) == "number" && value >= 1 && value <= 6;
сделал

2018-04-16 15:17 UTC, Shancle commented on lib/getPokerHand.js
> +function getTwoLargestValue(array) {
так асимптотическая сложность увеличится, но раз у нас всегда 5 элементов то это не имеет значения, переделал.

2018-04-20 14:57 UTC, Zhigalov approved these changes
Решение принято!

2018-04-20 14:57 UTC, Zhigalov commented on lib/getPokerHand.js
> +        throw new Error("Bad input parameter to function")
Совсем круто будет если уточнишь причину, по которой возникла ошибка

2018-04-20 14:57 UTC, closed without merging

2018-04-20 21:16 UTC, Shancle commented on lib/getPokerHand.js
> +        throw new Error("Bad input parameter to function")
Не совсем понял вопрос, если имеется ввиду для чего я в таком случае кидаю ошибку, то это потому что без этих условий я не могу считать комбинацию.