Мария Хорькова
urfu-2017/autotests-task-01 pull request #21
Opened 2018-04-10 22:50 UTC by maria-kho

2018-04-16 17:17 UTC, mrprovoker requested changes
Привет. 
Не все случаи учтены. Доделай код и допиши тесты

2018-04-16 17:17 UTC, mrprovoker commented on lib/getPokerHand.js
> +    if (counter[0] === 5) {
много if наталкивают на мысль использовать switch case

2018-04-16 17:17 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +    it('should throw an error for array size other than 5', () => {
Негативные кейсы можно было описать внутри отдельного describe для наглядности

2018-04-16 17:17 UTC, mrprovoker commented on lib/getPokerHand.js
> +    if (dice.length !== 5) {
А если вообще аргумента нет?
Или аргумент не массив?

Нужно добавить на это проверки и написать на них тесты

2018-04-16 17:17 UTC, mrprovoker commented on lib/getPokerHand.js
> +            throw new Error('The value is not a number');
ошибка про то, что "Массив содержит не число"
А ниже, что "Массив должен содержать целые числа от 1 до 6"

2018-04-16 17:17 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +    it('should throw an error for not 1-6 integer values', () => {
по хорошему проверить еще граничное значение на левом конце, когда есть число 0

2018-04-18 19:36 UTC, maria-kho commented on lib/getPokerHand.js
> +            throw new Error('The value is not a number');
Разбила случаи по-другому. Или можно еще как-то лучше?

2018-04-18 19:41 UTC, mrprovoker approved these changes
Молодец!

Задание засчитано.

2018-04-18 19:41 UTC, mrprovoker commented on lib/getPokerHand.js
> +            throw new Error('The value is not an integer');
Пользователь передает массив (неверный) в качестве аргумента, а получает ошибку: "значение не целое". А что это будет значить? Что в качестве аргумента надо передавать не массив, а число?

Чтобы таких вопросов не возникало лучше раскрывать ошибку: "массив содержит не целое число" или т.п.

2018-04-18 19:41 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +    const cb = () => getPokerHand('meoow');
Если будешь серьезно заниматься автотестами, то советую в таких проверках писать явно что передали не то, что ожидалось.

Например, в данном случае можно было написать: ```getPokerHand('not array')```

2018-04-18 19:42 UTC, closed without merging