Ромасс Ольга
urfu-2017/autotests-task-01 pull request #28
Opened 2018-04-11 10:24 UTC by romassol

2018-04-16 17:29 UTC, mrprovoker requested changes
Привет. Я так понимаю ты новичок в Javascript и это не страшно.

Я тебе дал советы, как можно визуально улучшить код, а исправлять ли - выбирать тебе.

Для меня критично, чтобы ты дописала тесты на
в массиве есть дробное число (например, 3.5)
на вход ничего не передали

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +    return result;
можно проще: new Array(length).fill(0)

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +        throw new Error("Count of dice throw should equals " + countOfDice)
Старайся использовать один тип кавычек для строк, мы например предпочитаем одинарные '

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +    if(dice.length != countOfDice){
В Javascript проверку на равенство лучше делать через тройное равно (===), а неравенство через !==.
Это уменьшает количество ошибок в коде (иначе '1' == 1 - это true)

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +    if(!Array.isArray(dice))
Большинством разработчиков принято даже одну проверку писать в фигурных скобках, то есть
```
if (!Array.isArray(dice)) { 
    throw new Error('Input should be an array');
}
```

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +        throw new Error('Input should be an array')
в конце каждого выражения принято ставить ;

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +    for(var i = 0; i < dice.length; i++){
Старайся ставить пробелы перед { или после for. 
Таким образом твой код воспринимается проще для многих разработчиков.

2018-04-16 17:29 UTC, mrprovoker commented on lib/getPokerHand.js
> +function isYahtzee(dice){
а зачем передавать аргументом dice, если не используется в функции?

2018-04-16 17:29 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +    });
еще нужен тест на "Наивысшее очко"

2018-04-16 17:29 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +    });
Давай еще добавим тесты на дробное число в массиве и на случай, когда аргументы у ```getPokerHand()``` отсутствуют

2018-04-17 17:37 UTC, romassol commented
Можете подсказать как перезалить проект со всеми изменениями? Просто создать новый Pull request?

2018-04-18 17:10 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +function getCombinationTest(name, dice) {
я советую такие функции (которые строят тесты) начинать со слова run, то есть например для этой ```runCombinationTest```

2018-04-18 17:10 UTC, mrprovoker commented on tests/getPokerHand-test.js
> +            'Dice should contains only 5 integer numbers from 1 to 6');
а как так получилось, что для всех негативных тестов ожидается одна и та же ошибка?

2018-04-20 15:00 UTC, mrprovoker commented
@romassol ответь на вопрос в комментарии

2018-04-20 15:31 UTC, romassol commented on tests/getPokerHand-test.js
> +            'Dice should contains only 5 integer numbers from 1 to 6');
Не знаю как так получилось, решила, что так будет лучше, переделаю сейчас

2018-04-21 15:06 UTC, mrprovoker approved these changes
Молодец!
Задание засчитано

2018-04-21 15:06 UTC, closed without merging