Макаркин Александр Евгеньевич
urfu-2017/autotests-task-01 pull request #35
Opened 2018-04-11 13:43 UTC by NeosKsen

done

2018-04-11 14:01 UTC, NeosKsen commented
В негативных тестах мне кажется что хватило бы первых трех тестов, но куча людей сказали мне что их должно быть много, кто из нас прав?

2018-04-18 11:39 UTC, taffimay requested changes
- тесты на Наивысшее очко (Лучшая кость - 5, 6) лучше так и назвать "Наивысшее очко", плюс надо сделать тестам "Лучшая кость-6" разные названия, они же разные.
- негативные проверки лучше реализовать через assert.throws
- "should throw error expected array of length 5" - кажется, неточное название, ведь у нас исключение, если длина массива не 5, а не 5.
- У трех тестов (2 - "should throw error expected array of length 5" и третий на пустой массив) слишком похожие названия, надо переназвать
- аналогично тесты "error 2 array element is not a valid number for" - при запуске сложно будет понимать где что именно проверяется
- надо добавить еще негативную проверку, что в массиве есть число больше 6

2018-04-25 10:03 UTC, NeosKsen commented
тесты на Наивысшее очко (Лучшая кость - 5, 6) лучше так и назвать "Наивысшее очко", плюс надо сделать тестам "Лучшая кость-6" разные названия, они же разные.
Не понял данный комментарий, в моей программе вариант наивысшее очко реализован в двух вариантах, для 5 и для 6(тз было не однозначным). Что имеется в виду под разными названиями тестов? Они отличались друг от друга только 6 и 0x6.**(переделал логику на вариант с "Наивысшее очко")**
негативные проверки лучше реализовать через assert.throws
Но ведь они уже реализованы через assert.throws, я только 1 штуку оставил без него ради интереса**(убрал её)**
"should throw error expected array of length 5" - кажется, неточное название, ведь у нас исключение, если длина массива не 5, а не 5.
Не понял данный комментарий, если я кидаю массив длины !=5, то получаю ошибку "ожидал массив длины 5"
У трех тестов (2 - "should throw error expected array of length 5" и третий на пустой массив) слишком похожие названия, надо переименовать
Можете привести пример? я не понимаю что значит переименовать тесты, это же просто текст "Должен бросить ошибку ожидался массив длины 5  для "какая-то строка""
аналогично тесты "error 2 array element is not a valid number for" - при запуске сложно будет понимать где что именно проверяется
Я не понимаю, при ошибке я увижу "2 элемент массива не валидное число.",  все же понятно
надо добавить еще негативную проверку, что в массиве есть число больше 6
Тестировал белым ящиком, поэтому была только проверка с числом ниже 1**(добавил с 8)**

2018-04-25 11:28 UTC, taffimay requested changes
Более приятные тексты исключений могут выглядеть так:
should throw error if array length < 4
should throw error if array length > 5
should throw error if argument not array

1. тесты же каждый про разное, ошибка должна это отражать явно
2. человек, который будет смотреть на эти исключения подряд текстом, не сразу увидит отличия, разглядывать, сколько там единиц в массиве - не очень удобно

Остальное ок

2018-05-23 11:04 UTC, taffimay approved these changes
Молодец

2018-05-23 11:05 UTC, closed without merging