Останин Игорь
urfu-2017/autotests-task-01 pull request #6
Opened 2018-04-07 08:57 UTC by BrittleFoot

2018-04-15 15:52 UTC, sunkitten13 requested changes
Привет! У тебя не все ветки покрыты тестами. В идеале в Details должно быть 100% покрытие по всем пунктам. Попробуй найти, чего именно не хватает.

2018-04-17 18:26 UTC, BrittleFoot commented
Привет! Ага, там дефолтная ветка `switch` никогда не вызывалась, потому что до этого было проверено, что возможный набор значений ограничен. Подправил.

2018-04-22 18:30 UTC, sunkitten13 requested changes
Привет! Хорошо, но есть пара замечаний:
1. Нет проверки, когда на вход ничего не подается. Данную проверку стоит вынести отдельно.
2. Объединены в один тест негативные проверки, что числа находятся в диапазоне от 1 до 6. А если в массиве будет и число 0, и число 7? По правилам, нельзя объединять негативные проверки.

2018-04-25 08:32 UTC, sunkitten13 approved these changes
Зачтено.

2018-04-25 08:55 UTC, closed without merging