Комулов Андрей
urfu-2017/autotests-task-01 pull request #8
Opened 2018-04-09 12:35 UTC by Andreyproger

2018-04-10 13:47 UTC, Zhigalov requested changes
При попытке запустить код получаю ошибку
```
/home/travis/build/urfu-2017/autotests-task-01/lib/getPokerHand.js:22
			answer[item] = 0:
			                ^
SyntaxError: Unexpected token :
```

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> + **/
Я не понял к чему относится этот комментарий.
Он должен идти прямо перед функцией, которую описывает

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> +	// use Энтропия Шеннона
Что?

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> +    if(dice.some(j => isNaN(j) || j <= 0 || j >= 7)){
Элемент массива может быть числом в диапазоне от 1 до 6, но все равно не подходящий под задачу. Например, `4.5`

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> +    if(dice.some(j => isNaN(j) || j <= 0 || j >= 7)){
Для справки
```js
isNaN([1]); // false
```

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> +    const gFM = getFrequencyMap(dice)
`gFM`? В JavaScript не принято давать такие названия переменным.
Я бы назвал `frequencyMap`

2018-04-10 13:47 UTC, Zhigalov commented on lib/getPokerHand.js
> +    const counts = gFM
Эта переменная нигде не используется

2018-04-10 13:47 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +	    	assert.equal(actual, `Пара`);
Очень много тестов для "Пары". В чем разница? Они не увеличивают покрытие кода

2018-04-10 13:47 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +	});
Где проверка на тройку?

2018-04-10 13:47 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +	        const actual = () => getPokerHand([]);
Описание теста не соответствует проверке

2018-04-10 13:47 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +	        const actual = () => getPokerHand([]);
Но `[]` это же массив!

2018-04-12 14:57 UTC, Zhigalov commented
Жду исправлений

2018-04-13 18:38 UTC, Andreyproger commented
Исправления смогу внести только завтра.12.04.2018, 19:57, "Sergey Zhigalov" <notifications@github.com>:Жду исправлений

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  


 --------------------С уважением, Андрей Комулов

2018-04-16 16:21 UTC, Andreyproger commented
Перезалил код на github через браузер, т.к. через командную строку не вышло. Можно так проверить? Если нельзя, то вышли, по возможности, команду для перезаписи через Git. 13.04.2018, 23:38, "Angus Young" <crashc@yandex.ru>:Исправления смогу внести только завтра. 12.04.2018, 19:57, "Sergey Zhigalov" <notifications@github.com>:Жду исправлений—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    --------------------С уважением, Андрей Комулов    --------------------С уважением, Андрей Комулов 

2018-04-20 14:53 UTC, Zhigalov commented
Твой код не собирается. Ошибка:

2018-05-06 15:28 UTC, Zhigalov reviewed
Очень хорошо, осталось совсем чуть-чуть!

2018-05-06 15:28 UTC, Zhigalov commented on lib/getPokerHand.js
> +        throw new TypeError('Need throw 6 dices');
В игре пять костей, а не шесть

2018-05-06 15:28 UTC, Zhigalov commented on lib/getPokerHand.js
> +            throw new TypeError('Значения должны быть целые');
Почему у тебя некоторые сообщения на русском, а некоторые на английском?

2018-05-06 15:28 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +    describe('negative2', () => {
Почему эти два теста лежат в отдельном `describe`? 
Чем они примечательны? Можно ли их опустить на уровень "негативных тестов"?

2018-05-06 15:28 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +});
Я обычно оформляю тесты так:
```js
describe(`getPokerHand `, () => {
    describe('positive', () => {
        // Здесь собираю тесты на позитивные сценарии
    });
    describe('positive', () => {
        // Здесь собираю негативные тесты
    });
});
```

2018-05-06 15:28 UTC, Zhigalov commented on tests/getPokerHand-test.js
> +});
Старайся сделать так, чтобы в файле был только один `describe`, всё остальное вкладывай в него.

2018-05-07 08:51 UTC, Andreyproger commented
 Так нельзя зачесть?06.05.2018, 20:28, "Sergey Zhigalov" <notifications@github.com>:@Zhigalov commented on this pull request.Очень хорошо, осталось совсем чуть-чуть!In lib/getPokerHand.js:> -    return 'Покер';
-}
-
-module.exports = getPokerHand;
+/**
+ * Определение комбинации в броске
+ *
+ * @param {Array} dice пять костей, для которых нужно определить комбинацию
+ * @returns {String} название комбинации
+ */
+function getPokerHand(dice) {
+    if (!Array.isArray(dice)) {
+        throw new TypeError('You should enter Array');
+    }
+    if (dice.length !== 5) {
+        throw new TypeError('Need throw 6 dices');
В игре пять костей, а не шестьIn lib/getPokerHand.js:> +/**
+ * Определение комбинации в броске
+ *
+ * @param {Array} dice пять костей, для которых нужно определить комбинацию
+ * @returns {String} название комбинации
+ */
+function getPokerHand(dice) {
+    if (!Array.isArray(dice)) {
+        throw new TypeError('You should enter Array');
+    }
+    if (dice.length !== 5) {
+        throw new TypeError('Need throw 6 dices');
+    }
+    for (i=0 ; i < dice.length; i++) {
+        if (!isInteger(dice[i])) {
+            throw new TypeError('Значения должны быть целые');
Почему у тебя некоторые сообщения на русском, а некоторые на английском?In tests/getPokerHand-test.js:> +        } catch (error) {
+            assert.equal(error.message, 'Need throw 6 dices');
+        }
+    });
+    it('Бросить нужно не более 5', () => {
+        try {
+            getPokerHand([1,2,3,4,4,4,4]);
+            throw new Error('`getPokerHand` should throw error')
+        } catch (error) {
+            assert.equal(error.message, 'Need throw 6 dices');
+        }
+    });
+
+    });
+
+    describe('negative2', () => {    
Почему эти два теста лежат в отдельном describe?Чем они примечательны? Можно ли их опустить на уровень "негативных тестов"?In tests/getPokerHand-test.js:> +            getPokerHand([1, 2, 3, 4, 7]);
+            throw new Error('`getPokerHand` should throw error')
+        } catch (error) {
+            assert.equal(error.message, 'Значения должны быть в промежутке от 1 до 6');
+        }
+    });
+    it('Значения должны быть целые', () => {
+        try {
+            getPokerHand([1.7, 2, 3, 5.4, 5.1]);
+            throw new Error('`getPokerHand` should throw error')
+        } catch (error) {
+            assert.equal(error.message, 'Значения должны быть целые');
+        }
+    });
+
+});
Я обычно оформляю тесты так:describe(`getPokerHand `, () => {
    describe('positive', () => {
        // Здесь собираю тесты на позитивные сценарии
    });
    describe('positive', () => {
        // Здесь собираю негативные тесты
    });
});In tests/getPokerHand-test.js:> +            getPokerHand([1, 2, 3, 4, 7]);
+            throw new Error('`getPokerHand` should throw error')
+        } catch (error) {
+            assert.equal(error.message, 'Значения должны быть в промежутке от 1 до 6');
+        }
+    });
+    it('Значения должны быть целые', () => {
+        try {
+            getPokerHand([1.7, 2, 3, 5.4, 5.1]);
+            throw new Error('`getPokerHand` should throw error')
+        } catch (error) {
+            assert.equal(error.message, 'Значения должны быть целые');
+        }
+    });
+
+});
Старайся сделать так, чтобы в файле был только один describe, всё остальное вкладывай в него.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    --------------------С уважением, Андрей Комулов 

2018-05-14 06:29 UTC, Zhigalov approved these changes
Задание принято!

2018-05-14 06:29 UTC, closed without merging

2018-05-14 16:34 UTC, Andreyproger commented
Добрый вечер. Сергей, вторая задача по автотестам первый раз была отправлена в срок. В связи с окончанием учебы и написанием диплома не представлялось возможности её поправить. Поправил вместе с первой. Если имеется возможность - прими её пожалуйста.   14.05.2018, 11:29, "Sergey Zhigalov" <notifications@github.com>:Closed #8.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    --------------------С уважением, Андрей Комулов 